(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var C3=function(a){a.ea("cardstatechange",a.Hh()&&a.Lk()?1:0)},D3=function(a,b){var c=g.Na(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},mUa=function(a){var b=g.un(a);
a=g.An(a);return new g.cn(b.x,b.y,a.width,a.height)},nUa=function(a){return Math.pow(a,3)},oUa=function(a){return 3*a*a-2*a*a*a},G3=function(a){a=g.Qa(a);
delete E3[a];g.af(E3)&&F3&&F3.stop()},qUa=function(){F3||(F3=new g.L(function(){pUa()},20));
var a=F3;a.isActive()||a.start()},pUa=function(){var a=g.Ta();
g.Oe(E3,function(b){rUa(b,a)});
g.af(E3)||qUa()},H3=function(a,b,c,d){g.yr.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.S=b;this.duration=c;this.J=d;this.coords=[];this.progress=this.K=0;this.D=null},rUa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;sUa(a,a.progress);1==a.progress?(a.i=0,G3(a),a.onFinish(),a.bx()):a.Jc()&&a.KC()},sUa=function(a,b){"function"===typeof a.J&&(b=a.J(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.S[c]-a.u[c])*b+a.u[c]},tUa=function(a,b){g.Ee.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.i},I3=function(a,b,c,d,e){H3.call(this,b,c,d,e);
this.element=a},J3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
I3.call(this,a,b,c,d,e)},K3=function(a){g.I.call(this);
this.u=a||window;this.i=[]},L3=function(a){return a.baseUrl||null},M3=function(a,b){return g.Gp(g.co(a,b,void 0),function(c){return!!c})},uUa=function(a,b,c){function d(M){var sa,Fa,kb,Wa=M.hovercardButton;
if(!Wa)return null;Wa=Wa.subscribeButtonRenderer;if(!Wa)return null;var Cb=f(Wa.unsubscribedButtonText),$b=f(Wa.subscribedButtonText);if(Wa.subscribed){var Ya=f(Wa.subscriberCountWithUnsubscribeText);var fd=f(Wa.subscriberCountText)}else Ya=f(Wa.subscriberCountText),fd=f(Wa.subscriberCountWithSubscribeText);var Qb=null;return M.signinEndpoint&&(Qb=D3(M,"signinEndpoint","webNavigationEndpointData","url"),Qb||(Qb=null===(kb=null===(Fa=null===(sa=Wa.signInEndpoint)||void 0===sa?void 0:sa.commandMetadata)||
void 0===Fa?void 0:Fa.webCommandMetadata)||void 0===kb?void 0:kb.url),!Qb)?null:Cb&&($b||Qb)?{subscribed:Wa.subscribed,subscribeText:Cb,subscribeCount:Ya,unsubscribeText:$b,unsubscribeCount:fd,enabled:Wa.enabled,signinUrl:Qb,classic:M.useClassicSubscribeButton}:null}
function e(M){if(M){var sa=[],Fa=M.videoId;Fa&&sa.push("v="+Fa);(Fa=M.playlistId)&&sa.push("list="+Fa);(M=M.startTimeSeconds)&&sa.push("t="+M);return"/watch?"+sa.join("&")}}
function f(M){if(!M)return null;var sa=M.simpleText;return sa?sa:M.runs?g.co(M.runs,function(Fa){return Fa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,v=null,x=!1,y=null,z=null,E=null,H=null,G=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=D3(l,"browseEndpoint","browseId"))v=x,m="/channel/"+v;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):z=f(b.subscribersText)}else"WEBSITE"===
h?((E=D3(l,"urlEndpoint","url"))&&(m=E),n=!0,p="new",E=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(G=f(b.additionalFeesText)),(n=D3(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=D3(b,"title","accessibility","accessibilityData","label");var K=b.endpoint?b.endpoint.clickTrackingParams:null,X="";if(b.metadata){var ba=f(b.metadata);ba&&(X=ba)}return{id:"element-"+c,type:h,title:f(b.title),metadata:X,callToAction:f(b.callToAction),
QK:b.image,iconUrl:E,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:v,subscribeButton:y,subscribersText:z,isSubscribe:x,targetUrl:m||null,dU:n,sessionData:K?{itct:K}:null,PY:p,fv:a?a:null,gU:b.isPlaceholder,impressionUrls:M3(b.impressionUrls||[],L3),TT:M3(b.hovercardShowUrls||[],L3),clickUrls:M3(l.loggingUrls||[],L3),visualElement:g.Dx(b.trackingParams),
productPrice:H,additionalFeesText:G}},N3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:M3(a.impressionUrls||[],L3),elements:M3(a.elements||[],function(d,e){return uUa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Dx(a.trackingParams));return c},O3=function(a){g.rM.call(this,a);
this.B=this.endscreen=null;this.i={};this.D={};this.C=this.u=null;this.K=[];this.X=!0;this.J=0;a=a.U();this.S=g.ZD(a)||g.cE(a);this.events=new g.pC(this);g.J(this,this.events);this.events.T(this.player,g.Ly("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.My("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Ab);this.events.T(window,"focus",this.PX);this.load();var b=g.ph("STYLE");(g.ch("HEAD")[0]||document.body).appendChild(b);g.De(this,function(){g.th(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},vUa=function(a){return a.player.getVideoData().D?"current":a.S?"new":"current"},P3=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},wUa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=N3(f,vUa(a))));Q3(a,f)},
urlParams:{v:c},withCredentials:!0};a.S&&(c.urlParams.ptype="embedded");var d=b.Nq;d&&(c.postParams={ad_tracking:d});if(b=g.Cua(b))if(b=g.gg(b),b=g.Zf(b))a.B=g.Jt(b,c)},Q3=function(a,b,c){c=void 0===c?!0:c;
a.player.gf("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.J=0;if((a.endscreen=b)&&b.elements){c&&xUa(a);c=[];d=new g.Jy(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().isMobile||(a.u=new g.V({G:"div",L:"ytp-ce-shadow"}),g.dM(a.player,a.u.element,4),a.C=new g.JK(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=yUa(a,e);if(f){a.i[e.id]=f;a.D[e.id]=e;g.dM(a.player,f.element,4);var h=new g.Jy(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);zUa(a,
f,e)}else g.Px(new g.Jv("buildEndscreenElement null",e))}a.player.Od(c);a.Ab()}},xUa=function(a){var b=g.Gx(),c=g.Hx();
c&&b&&a.endscreen.visualElement&&g.Xx(void 0,c,b,[a.endscreen.visualElement])},yUa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ia:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.fv||"","aria-hidden":"true"},V:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:R3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:S3(a,b.targetUrl),tabindex:"-1"},V:[{G:"div",Ia:["ytp-ce-video-title"].concat(g.u(c)),W:{dir:g.Dr(b.title||
"")},va:b.title},{G:"div",L:"ytp-ce-video-duration",va:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ia:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.fv||"","aria-hidden":"true"},V:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:R3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:S3(a,
b.targetUrl),tabindex:"-1"},V:[{G:"div",Ia:["ytp-ce-playlist-title"].concat(g.u(c)),W:{dir:g.Dr(b.title||"")},va:b.title},{G:"div",L:"ytp-ce-playlist-count",V:[{G:"div",L:"ytp-ce-playlist-icon"},{G:"div",L:"ytp-ce-playlist-count-text",va:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={G:"div",Ia:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.fv||"","aria-hidden":"true"},V:[{G:"div",L:"ytp-ce-element-shadow"},
{G:"div",L:"ytp-ce-expanding-overlay",V:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",V:[{G:"div",L:"ytp-ce-expanding-overlay-body",V:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",V:[{G:"a",Ia:["ytp-ce-channel-title","ytp-ce-link"],W:{href:S3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Dr(b.title||"")},va:b.title},b.subscribeButton?{G:"div",L:"ytp-ce-subscribe-container",V:[{G:"div",L:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{G:"div",L:"ytp-ce-channel-subscribers-text",va:b.subscribersText}:"",b.metadata?{G:"div",Ia:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],va:b.metadata}:""]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:R3(b)}]};c=new g.V(c);var d=g.dh(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.N(d,"ytp-ce-subscribe-button");if(a.player.U().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.uN(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",Ia:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.fv||"","aria-hidden":"true"},V:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",V:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},
{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",V:[{G:"div",L:"ytp-ce-expanding-overlay-body",V:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",V:[{G:"div",L:"ytp-ce-website-title",W:{dir:g.Dr(b.title||"")},va:b.title},{G:"div",L:"ytp-ce-website-metadata",va:b.metadata},{G:"a",Ia:["ytp-ce-website-goto","ytp-ce-link"],W:{href:S3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:R3(b)},{G:"div",
L:"ytp-ce-expanding-icon",W:AUa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",L:"ytp-ce-merchandise-price-container",V:[{G:"div",L:"ytp-ce-merchandise-price",va:b.productPrice}]},b.additionalFeesText&&c.V.push({G:"div",L:"ytp-ce-merchandise-additional-fees",va:b.additionalFeesText})),a={G:"div",Ia:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.fv||"","aria-hidden":"true"},V:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",
V:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",V:[{G:"div",L:"ytp-ce-expanding-overlay-body",V:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",V:[{G:"div",L:"ytp-ce-merchandise-title",W:{dir:g.Dr(b.title||"")},va:b.title},c,{G:"div",L:"ytp-ce-merchandise-metadata",va:b.metadata},{G:"a",Ia:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:S3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},
{G:"div",L:"ytp-ce-expanding-image",W:R3(b)},{G:"div",L:"ytp-ce-merchandise-invideo-cta-container",V:[{G:"div",L:"ytp-ce-merchandise-invideo-cta",va:b.callToAction||void 0}]}]},c=new g.V(a)}b.gU&&g.N(c.element,"ytp-ce-placeholder");return c},R3=function(a){if(a.QK)var b=a.QK.thumbnails;
return AUa(b?b[b.length-1].url:null)},AUa=function(a){return a?{style:"background-image: url("+a+")"}:{}},zUa=function(a,b,c){function d(m){m&&(b.Ra("blur",function(){"none"!=m.style.display&&a.X&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.J+=m;0<a.J?(g.N(b.element,"ytp-ce-force-expand"),T3(a,c.id,!0)):(g.pr(b.element,"ytp-ce-force-expand"),g.pr(b.element,"ytp-ce-element-hover"),T3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ra("mouseenter",function(){U3(a,b,c)});
b.Ra("mouseleave",function(){V3(a,b,c)});
a.player.U().isMobile||b.Ra("click",function(){g.N(b.element,"ytp-ce-element-hover")});
b.Ra("click",function(m){BUa(a,c,m)});
b.Ra("keypress",function(m){BUa(a,c,m)});
b.Ra("focus",function(){U3(a,b,c)});
b.Ra("blur",function(){V3(a,b,c)});
b.Ra("touchstart",function(){U3(a,b,c)});
var l=g.fh("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.pr(b.element,"ytp-ce-element-hover");g.pr(b.element,"ytp-ce-force-expand")});
b.Ra("keydown",function(m){a.X=9===m.keyCode&&!m.shiftKey});
d(g.fh("ytp-sb-subscribe",b.element));d(g.fh("ytp-sb-unsubscribe",b.element));b.Ra("focus",f);b.Ra("blur",h)},BUa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.nr(d,"ytp-ce-element");){g.nr(d,"subscribe-label")&&W3(a,b);
if(g.nr(d,"ytp-ce-channel-subscribe"))return;d=g.uh(d)}if(!d||g.nr(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])V3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.PY)W3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.gg(S3(a,b.targetUrl)),c=g.Zf(c),g.iL(c,void 0,b.sessionData);else{var e=a.player.getVideoData().D,f=function(){var h=S3(a,b.targetUrl),l=b.sessionData,m=g.tt(h);e&&m&&(m.v||m.list)?a.player.hk(m.v,l,m.list,!1):
g.hL(h,l)};
W3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},S3=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.AE(a)+b}else return"";return b},U3=function(a,b,c){g.nr(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.N(b.element,"ytp-ce-element-hover"):a.player.U().isMobile?(new g.L(function(){g.N(b.element,"ytp-ce-element-hover")},200)).start():g.N(b.element,"ytp-ce-element-hover"),X3(a,c.TT),T3(a,c.id,!0))},V3=function(a,b,c){g.pr(b.element,"ytp-ce-element-hover");
g.pr(b.element,"ytp-ce-force-expand");T3(a,c.id,!1)},T3=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.O(a.i[e].element,"ytp-ce-element-shadow-show",c)},X3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||P3(a))c&&c();else{b=CUa(a,b);var e=0,f=!1,h=new g.L(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Mu(b[a],d)}},W3=function(a,b,c){X3(a,b.clickUrls,c);
(a=g.Hx())&&b.dU&&g.cy(a,b.visualElement)},CUa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(DUa(b[d],c));return a},DUa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},EUa=function(a){return"string"===typeof a?a:""},Y3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},FUa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},Z3=function(a){return a.value?a.value:null},$3=function(a){if(!a)return null;
var b=g.gg(EUa(a.value));b=g.Zf(b);if(!b)return null;var c=Y3(a.target,GUa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new FUa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},HUa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},KUa=function(a){if(!a)return null;
var b=Y3(a.type,IUa),c=Y3(a.trigger,JUa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=$3(a?a:null);return b?new HUa(b,c,a):null},LUa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},NUa=function(a){return(a=MUa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},MUa=function(a,b){return g.Wb(a.action,b,void 0)},OUa=function(a,b){this.context=a;
this.i=b},b4=function(a){return a.customMessage?a4("div","iv-card-message",a.customMessage):""},c4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",L:"iv-card-image",W:{style:a},V:c}},d4=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(a4("li","",c.value));return{G:"ul",L:"iv-card-meta-info",V:b}},a4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Dr(c);return{G:a,W:b,va:c}},PUa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Oy&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Oy+");");c.dir=g.Dr(a.customMessage);var d=[{G:"span",va:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",L:"iv-card-link-icon"}));return{G:"div",Ia:b,W:c,V:d}},e4=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},QUa=function(a,b){this.merchant=a;
this.price=b},RUa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},SUa=function(a,b){return b?b:RUa(a)?"current":"new"},f4=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.ib=!1;this.Va=new Map;this.Sa=new Map;this.context.I.addEventListener(g.Ly("annotations_module"),function(d){(d=c.Va.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.My("annotations_module"),function(d){(d=c.Sa.get(d))&&d.apply(c)})},g4=function(a,b,c,d,e,f,h){a.context.i.Ra(b,"click",function(l){a.LC(c,d,e,f||[],h||0,l)});
a.context.i.Ra(b,"touchstart",function(){a.ib=!1});
a.context.i.Ra(b,"touchmove",function(){a.ib=!0})},TUa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},h4=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
bP:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
FB:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},k4=function(a,b,c){f4.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.Ka=this.zb=this.B=this.isInitialized=!1;this.ya=null;this.cards=[];this.ob=this.S=this.Ja=this.D=this.Na=this.i=null;this.Z=[];this.K=this.Me=this.Ba=null;this.J=0;this.Aa=new g.L(g.Ka,c.Y.Ae?4E3:3E3);g.J(this,this.Aa);this.bb=new g.L(g.Ka);g.J(this,this.bb);this.ma=new OUa(c,function(e,f,h,l,m,n){g4(d,e,f,h,l,m,n)});
this.X=new g.V({G:"div",L:"iv-drawer",W:{id:"iv-drawer"},V:[{G:"div",L:"iv-drawer-header",W:{"aria-role":"heading"},V:[{G:"span",L:"iv-drawer-header-text"},{G:"button",Ia:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",L:"iv-drawer-content"}]});g.J(this,this.X);this.C=this.X.element;this.Xa=new g.JK(this.X,330);g.J(this,this.Xa);this.qb=g.fh("iv-drawer-header-text",this.C);this.u=g.fh("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.zb&&i4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.zb=d.B)&&j4(d)})},UUa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){i4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){j4(a)});
var c=b.headerText;g.wh(a.qb,c);a.S&&a.S.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ba=g.Dx(b.trackingParams);a.K=g.Dx(b.closeTrackingParams);a.Me=g.Dx(b.iconTrackingParams)},VUa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.J;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.Qy(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:l4(a,c,b,d),sponsored:!1,tracking:h4(d,e,d.command),Wl:d.trackingParams?g.Dx(d.trackingParams):null,gj:e.trackingParams?
g.Dx(e.trackingParams):null,Me:f&&f.trackingParams?g.Dx(f.trackingParams):null,imageUrl:m4(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.Qy(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Oy:null,title:d.title?g.Qy(d.title):"",customMessage:d.callToAction?g.Qy(d.callToAction):"",url:d.command.urlEndpoint.url?$3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};n4(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"collaborator",teaserText:g.Qy(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:l4(a,c,b,d),sponsored:!1,tracking:h4(d,e,d.endpoint),Wl:d.trackingParams?g.Dx(d.trackingParams):null,gj:e.trackingParams?g.Dx(e.trackingParams):null,Me:f&&f.trackingParams?
g.Dx(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.Qy(d.customText):null,profileImageUrl:m4(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.Qy(d.channelName):"",metaInfo:[d.subscriberCountText?g.Qy(d.subscriberCountText):""],url:$3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};
n4(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"playlist",teaserText:g.Qy(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:l4(a,c,b,d),sponsored:!1,tracking:h4(d,e,d.action),Wl:d.trackingParams?g.Dx(d.trackingParams):
null,gj:e.trackingParams?g.Dx(e.trackingParams):null,Me:f&&f.trackingParams?g.Dx(f.trackingParams):null,Wx:m4(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.Qy(d.customMessage):null,playlistVideoCount:g.Qy(d.playlistVideoCount),title:d.playlistTitle?g.Qy(d.playlistTitle):"",metaInfo:[d.channelName?g.Qy(d.channelName):"",d.videoCountText?g.Qy(d.videoCountText):""],url:$3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:TUa(d.action)})};n4(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"video",teaserText:g.Qy(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:l4(a,c,b,d),sponsored:!1,tracking:h4(d,e,d.action),Wl:d.trackingParams?g.Dx(d.trackingParams):null,gj:e.trackingParams?g.Dx(e.trackingParams):null,Me:f&&f.trackingParams?g.Dx(f.trackingParams):
null,Wx:m4(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.Qy(d.lengthString):null,customMessage:d.customMessage?g.Qy(d.customMessage):null,title:d.videoTitle?g.Qy(d.videoTitle):"",metaInfo:[d.channelName?g.Qy(d.channelName):"",d.viewCountText?g.Qy(d.viewCountText):""],isLiveNow:!!d.badge,url:$3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:TUa(d.action)})};n4(a,b)}a.J++},m4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===
a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},l4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},XUa=function(a,b){if(b=WUa(a,b))b===a.i&&(a.i=null),a.I.removeCueRange(b.card.id),g.th(b.MD),g.ec(a.cards,b),a.Ry(),o4(a)},i4=function(a,b,c){if(!a.B){a.Xa.show();
a.Na=new g.L(function(){g.N(a.context.I.getRootNode(),g.gT.IV_DRAWER_OPEN)},0);
a.Na.start();a.ya=g.wu(a.u,"mousewheel",function(h){a.Aa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.Hx();d&&a.Ba&&a.K&&g.ay(d,[a.Ba,a.K]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.AM||(f.AM=!0,YUa(a.context.logger,f.card.tracking.impression,b)),d&&g.ay(d,[f.card.Wl]);C3(a.I);c&&(a.D=new g.L(function(){a.Ja=a.S;a.ob.focus()},330),a.D.start())}},j4=function(a){a.B&&(a.Xa.hide(),g.xu(a.ya),a.ya=null,g.pr(a.context.I.getRootNode(),g.gT.IV_DRAWER_OPEN),a.B=!1,C3(a.I),a.D&&a.D.stop(),a.D=new g.L(function(){a.Ja&&(a.Ja.focus(),a.Ja=null)},330),a.D.start())},
$Ua=function(a){g.or(a.element,[g.gT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.dM(a.I,a.C,5);ZUa(a);a.S=g.fh("ytp-cards-button",a.I.getRootNode());a.ob=g.fh("iv-drawer-close-button",a.C);a.isInitialized=!0},ZUa=function(a){var b=g.fh("iv-drawer-close-button",a.C);
a.context.i.Ra(b,"click",a.AS,a);a.context.i.Ra(a.u,"touchend",function(){a.Aa.start()});
a.context.i.Ra(a.u,"scroll",a.NS,a);a.context.u.subscribe("onHideControls",function(){a.Ka=!0});
a.context.u.subscribe("onShowControls",function(){a.Ka=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ka=g.nr(a.I.getRootNode(),"ytp-autohide")});
a.Z.push(g.Su("iv-button-shown",a.mU,a));a.Z.push(g.Su("iv-button-hidden",a.lU,a));a.Z.push(g.Su("iv-teaser-shown",a.qR,a));a.Z.push(g.Su("iv-teaser-hidden",a.nU,a));a.Z.push(g.Su("iv-teaser-clicked",a.pR,a))},n4=function(a,b){a.isInitialized||$Ua(a);
XUa(a,b.id);var c=aVa(a,b);if(c){var d={card:b,MD:c.element,AM:!1},e=bVa(a,d);g.kc(a.cards,e,0,d);c.Ea(a.u,e);a.Ry();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.i=d,o4(a),cVa(a,d),i4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&dVa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){dVa(a,d)}),o4(a))}},aVa=function(a,b){switch(b.type){case "simple":a=a.ma;
var c=b.displayDomain?{G:"div",L:"iv-card-image-text",va:b.displayDomain}:void 0;var d=PUa(b);c={G:"div",Ia:["iv-card"],V:[{G:"a",L:"iv-click-target",W:{href:b.url?Z3(b.url)||"":""},V:[c4(b.imageUrl,c),{G:"div",L:"iv-card-content",V:[a4("h2",void 0,b.title),d]}]}]};c=new g.V(c);e4(a,g.eh("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.ma,c={G:"div",Ia:["iv-card","iv-card-channel"],V:[{G:"a",Ia:["iv-click-target"],W:{href:Z3(b.url)||"","data-ytid":b.channelId},V:[c4(b.profileImageUrl),
{G:"div",L:"iv-card-content",V:[b4(b),{G:"h2",L:"iv-card-primary-link",va:b.title},d4(b)]}]}]},c=new g.V(c),e4(a,g.eh("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.ma,c={G:"div",Ia:["iv-card","iv-card-playlist"],V:[{G:"a",L:"iv-click-target",W:{href:Z3(b.url)||""},V:[c4(b.Wx,{G:"div",L:"iv-card-image-overlay",V:[{G:"span",L:"iv-card-playlist-video-count",va:b.playlistVideoCount}]}),{G:"div",L:"iv-card-content",V:[b4(b),a4("h2","iv-card-primary-link",b.title),d4(b)]}]}]},c=new g.V(c),
e4(a,g.eh("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.ma;var e=!g.bc(b.offers);c=["iv-card"];d="";var f=PUa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",L:"iv-card-offer-price",va:f.price}),f.merchant&&e.push({G:"div",L:"iv-card-offer-merchant",va:f.merchant}),f={G:"div",V:e});e=b.url?Z3(b.url)||"":"";c={G:"div",Ia:c,W:{tabindex:"0"},V:[{G:"a",Ia:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",L:"iv-card-content",V:[b.sponsored?{G:"div",L:"iv-card-sponsored",V:["Sponsored",{G:"div",L:"iv-ad-info-container",V:[{G:"div",L:"iv-ad-info",va:"{{adInfo}}"},{G:"div",L:"iv-ad-info-icon-container",V:[{G:"div",L:"iv-ad-info-icon"},{G:"div",L:"iv-ad-info-callout"}]}]}]}:"",{G:"a",L:"iv-click-target",W:{href:e},V:[a4("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.ph("span");g.wh(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Bd(d,"adInfo");e4(a,g.eh("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.ma,d=b.videoDuration?{G:"span",L:"iv-card-video-duration",va:b.videoDuration}:void 0,f=b.isLiveNow?{G:"span",Ia:["yt-badge","yt-badge-live"],va:"LIVE NOW"}:null,e={G:"div",Ia:["iv-card","iv-card-video"],V:[{G:"a",L:"iv-click-target",W:{href:(null===(c=b.url)||void 0===c?void 0:Z3(c))||""},V:[c4(b.Wx,d),{G:"div",L:"iv-card-content",V:[b4(b),a4("h2","iv-card-primary-link",b.title),d4(b),f]}]}]},c=new g.V(e),
e4(a,g.eh("iv-click-target",c.element),b,b.url),c;default:return null}},bVa=function(a,b){if(0===a.cards.length)return 0;
a=g.Yb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},eVa=function(a){return a.i?"productListing"===a.i.card.type:g.eo(a.cards,function(b){return"productListing"===b.card.type})},o4=function(a){g.O(a.I.getRootNode(),"ytp-cards-shopping-active",eVa(a))},dVa=function(a,b){if(!g.nr(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.Hx(),d=a.i?a.i.card.Me:a.Me;
c&&d&&g.by(c,[d]);a.i=b;o4(a)}if(c="none"!=a.element.style.display)c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=1===c||3===c||d;c&&b.card.teaserDurationMs&&a.I.St(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.bb.isActive()||((!a.B||!a.Aa.isActive()&&a.Ka)&&cVa(a,b),a.bb.start(910+b.card.teaserDurationMs))}},cVa=function(a,b){a.X.ub?(b=new H3([0,
a.u.scrollTop],[0,b.MD.offsetTop],600,oUa),a.context.B.Ra(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ra(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.UJ(a.X,!0),a.u.scrollTop=b.MD.offsetTop,g.UJ(a.X,!1))},p4=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},WUa=function(a,b){return g.Wb(a.cards,function(c){return c.card.id===b})},q4=function(a,b,c){f4.call(this,a,b);
this.annotation=c;this.isActive=!1},fVa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},r4=function(a,b,c){q4.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.i=this.J=this.D=null},gVa=function(a,b){var c=void 0===c?0:c;
var d=mUa(b).width;g.sn(b,d);c=new J3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,nUa);g.J(a,c);a.context.B.Ra(c,"begin",function(){g.Bn(b,!0)});
c.play()},jVa=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ia:["iv-branding-context-name"],va:b.channel_name}),d=a.createElement({G:"div",Ia:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.uN(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.I),a.i.Ea(d));var f=a.createElement({G:"div",Ia:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ia:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Bn(h,!1);var l=a.createElement({G:"div",Ia:["branding-context-container-outer"]});l.appendChild(h);g.ln(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.L(function(){hVa(a,h,l)},500);
g.J(a,a.B);a.context.i.Ra(a.element,"mouseover",function(){iVa(a,h,l,f,b.image_height)});
a.context.i.Ra(a.element,"mouseout",function(){a.B.start()})}},iVa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.An(b);a.i||(b.style.width=g.rn(f.width,!0),c.style.width=g.rn(f.width,!0));g.ln(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.ln(d,"right","1px");a.C=!0;g.Bn(b,!0);a.D=new g.L(function(){g.N(this.element,"iv-branding-active")},0,a);
a.D.start()}},hVa=function(a,b,c){g.pr(a.element,"iv-branding-active");
a.J=new g.L(function(){g.Bn(b,!1);a.i||(c.style.width=g.rn(0,!0))},250);
a.J.start();a.C=!1},kVa=function(a,b,c,d,e,f,h){this.i=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.I=f;this.u=h},s4=function(a,b,c){q4.call(this,a,b,c);
var d=this;this.S=this.isCollapsed=this.X=!1;this.J=5E3;this.u=this.B=this.i=this.C=null;this.K=this.createElement({G:"div",Ia:["iv-promo-contents"]});this.D=new g.L(function(){d.i.setAttribute("aria-hidden","true");g.Bn(d.B,!1);g.Bn(d.u,!0)},700,this);
g.J(this,this.D)},lVa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.J=b.collapsedelay_ms||a.J;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=NUa(a.annotation),f=b.image_url;if(f){var h=a.createElement({G:"div",Ia:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({G:"span",L:"iv-promo-video-duration",va:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",L:"iv-promo-playlist-length",va:b.playlist_length.toString()}),h.appendChild(f));e&&g4(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",L:"iv-promo-txt"}),g.zg(f,Z3(e)),a.i=f):a.i=a.createElement({G:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",V:[{G:"strong",
va:b.text_line_1}]});var m=a.createElement({G:"p",V:[{G:"span",L:"iv-promo-link",va:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ia:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ia:["iv-button","iv-promo-button"],V:[{G:"span",L:"iv-button-content",va:f}]});var p=a.createElement({G:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&g4(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.N(a.i,
"iv-click-target");e&&g4(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",V:[{G:"span",va:b.text_line_1}]}),m=a.createElement({G:"p",V:[{G:"strong",va:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ia:["yt-badge","iv-promo-badge-live"],va:"LIVE NOW"})),g.N(a.i,"iv-click-target"),e&&g4(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.K.appendChild(a.i);p&&
a.K.appendChild(p);c=a.createElement({G:"div",L:"iv-promo-actions"});a.u=a.createElement({G:"button",Ia:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.i.Ra(a.u,"click",function(r){t4(a,5E3,r)});
c.appendChild(a.u);g.Bn(a.u,!1);a.context.i.Ra(a.element,"mouseover",a.xT,a);a.context.i.Ra(a.element,"mouseout",a.wT,a);a.context.i.Ra(a.element,"touchend",function(r){t4(a,5E3,r)});
a.B=a.createElement({G:"button",Ia:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.i.Ra(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.sT:a.rT,a);c.appendChild(a.B);g.or(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.K);a.element.appendChild(c)},t4=function(a,b,c){c.stopPropagation();
mVa(a);nVa(a,b);a.i.focus()},oVa=function(a){a.isCollapsed||a.S||a.C||(g.N(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},mVa=function(a){a.D.stop();
a.isCollapsed&&(g.qr(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.Bn(a.u,!1),g.Bn(a.B,!0))},nVa=function(a,b){a.C||(a.C=g.ni(function(){u4(this);
oVa(this)},b,a))},u4=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},pVa=function(a){this.I=a},YUa=function(a,b,c){b&&(c?v4(a,b.map(function(d){return g.Uq(d,c)})):v4(a,b))},v4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Mu(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},w4=function(a){g.rM.call(this,a);
var b=this;this.S=!1;this.loadNumber=0;this.J={};this.logger=new pVa(this.player);this.C=new g.pC(this);this.D=this.El=null;this.events=new g.pC(this);this.K=this.i=null;this.X=[];g.J(this,this.C);this.C.T(this.player,"onVideoAreaChange",function(){b.ea("onVideoAreaChange")});
this.C.T(this.player,"onHideControls",function(){b.ea("onHideControls")});
this.C.T(this.player,"onShowControls",function(){b.ea("onShowControls")});
this.C.T(this.player,"resize",function(d){b.ea("resize",d)});
this.C.T(this.player,"presentingplayerstatechange",function(d){b.ea("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.rR,this);this.subscribe("resize",this.KA,this);this.player.U().X.subscribe("vast_info_card_add",this.QN,this);g.J(this,this.events);this.Z=this.createElement({G:"div",L:"video-custom-annotations"});this.u=new g.V({G:"div",Ia:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.u);g.dM(this.player,this.u.element,4);this.u.hide();this.B=new g.V({G:"div",Ia:["ytp-iv-video-content"]});g.J(this,this.B);a=this.createElement({G:"div",L:"video-annotations"});
a.appendChild(this.Z);this.B.element.appendChild(a);this.Tq()&&this.load();var c=this.createElement({G:"style"});(g.ch("HEAD")[0]||document.body).appendChild(c);g.De(this,function(){g.th(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},qVa=function(a){a=a.createElement({G:"div",
Ia:["annotation","annotation-type-custom"]});g.Bn(a,!1);return a},rVa=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.UJ(a.u,b);g.UJ(a.B,b)},sVa=function(a,b,c){a.S=!0;
a.D=g.Jt(b,c)},tVa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Oa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(tVa(a,e))}return c},wVa=function(a){var b=a.player.getVideoData();
if(b.Va){var c=a.player.U().X.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Ct(h)&&h.responseXML?h.responseXML:null)&&x4(a,h)}};
g.Zt()&&(d.onFinish=uVa(a,d.onFinish));d.postParams={ic_only:"1"};vVa(d,c);a.S=!0;g.Jt(b.Va,d)}}},vVa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.yv&&(a.postParams.ic_coll=b.yv);b.Wy&&(a.postParams.ic_xml=b.Wy);b.Zx&&(a.postParams.ic_track=b.Zx)},xVa=function(a){var b=new g.V({G:"div"});
g.Bn(b.element,!1);var c=new k4(a.player,b.element,y4(a));g.J(c,b);b.Ea(a.u.element);c.Ix();return c},y4=function(a){if(!a.K){var b=new K3(a);
g.J(a,b);var c=new g.tl(a);g.J(a,c);a.K=new kVa(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.Nd)}return a.K},x4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Hx();if(e){var f=g.Gx();f&&g.Xx(void 0,e,f,[g.Dx(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=tVa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=Y3(f.type,yVa),p=Y3(f.style,zVa),r=EUa(f.data),t=0!==r.length?JSON.parse(r):{};var v=f.action;f=KUa;if(null==v)var x=null;else if(g.Na(v)){l=[];for(var y=g.q(v),z=y.next();!z.done;z=y.next()){var E=f(z.value);
E&&l.push(E)}x=l}else{var H=f(v);x=H?[H]:[]}e=m&&n?new LUa(m,n,p,x,t):null}else e=null}catch(sa){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var G=qVa(f),K=null;switch(l.type){case "branding":if(f.player.U().Nb)break;f.u.element.appendChild(G);K=new r4(G,y4(f),l);break;case "promotion":g.dM(f.player,G,4),K=new s4(G,y4(f),l)}K&&K.Ix();if(f=K)g.J(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=xVa(a),g.J(a,a.i));if("card"===e.type){c=a.i;var X=e&&e.data&&e.data.card_type;
f=e.data;if(X)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,bP:l.teaser_impression,FB:l.teaser_click},G=f.tracking_params||{},K=null,X){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Wl:G.card?g.Dx(G.card):null,gj:G.teaser?g.Dx(G.teaser):null,Me:G.icon?g.Dx(G.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:$3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};n4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Wl:G.card?g.Dx(G.card):
null,gj:G.teaser?g.Dx(G.teaser):null,Me:G.icon?g.Dx(G.icon):null,Wx:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:$3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};n4(c,e);break;case "productListing":f.signin_url&&(K=$3({target:"current",value:f.signin_url}));X=[];for(var ba=f.offers||[],M=0;M<ba.length;M++)X.push(new QUa(g.Og(ba[M].merchant),g.Og(ba[M].price)));e=
{id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Wl:G.card?g.Dx(G.card):null,gj:G.teaser?g.Dx(G.teaser):null,Me:G.icon?g.Dx(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Oy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:$3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Hfa:K,Gfa:f.signin_title?f.signin_title:void 0,Ffa:f.signin_message?f.signin_message:void 0,offers:X};n4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Wl:G.card?g.Dx(G.card):null,gj:G.teaser?
g.Dx(G.teaser):null,Me:G.icon?g.Dx(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Oy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:$3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};n4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,
autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Wl:G.card?g.Dx(G.card):null,gj:G.teaser?g.Dx(G.teaser):null,Me:G.icon?g.Dx(G.icon):null,Wx:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:$3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},n4(c,e)}}else UUa(a.i,e);c=!0}}c&&(C3(a.player),a.KA())},AVa=function(a,
b){var c=!1;
a.i||(a.i=xVa(a),g.J(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(VUa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.Qy(b.headerText):"",g.wh(c.qb,d),c.S&&c.S.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ba=b.trackingParams?g.Dx(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.Dx(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Me=b.icon.infoCardIconRenderer.trackingParams?
g.Dx(b.icon.infoCardIconRenderer.trackingParams):null,C3(a.player),a.KA())},BVa=function(a,b,c,d,e){if(!a.player.U().Nb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new HUa("openUrl","click",new FUa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Qy(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.Qy(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Qy(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.Qy(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.Qy(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.Qy(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new LUa(c,"branding","branding",f,d);l=qVa(a);a.u.element.appendChild(l);f=new r4(l,y4(a),f);f.Ix();g.J(f,f);a.J[c]=f}},uVa=function(a,b){return function(){var c=g.Ba.apply(0,arguments);
a.isDisposed()||a.X.push(g.Ku.Vf(function(){b.apply(null,g.u(c))}))}},CVa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.XL.prototype.St=g.da(17,function(a,b){var c=g.GM(this.vb());c&&c.St(a,b)});
var E3={},F3=null;g.Ua(H3,g.yr);g.k=H3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.i)this.progress=0,this.coords=this.u;else if(this.Jc())return!1;G3(this);this.startTime=a=g.Ta();-1==this.i&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.GA();this.Ai("play");-1==this.i&&this.Ai("resume");this.i=1;var b=g.Qa(this);b in E3||(E3[b]=this);qUa();rUa(this,a);return!0};
g.k.stop=function(a){G3(this);this.i=0;a&&(this.progress=1);sUa(this,this.progress);this.Ai("stop");this.bx()};
g.k.pause=function(){this.Jc()&&(G3(this),this.i=-1,this.Ai("pause"))};
g.k.xa=function(){0==this.i||this.stop(!1);this.Ai("destroy");H3.ye.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.KC=function(){this.Ai("animate")};
g.k.Ai=function(a){this.dispatchEvent(new tUa(a,this))};
g.Ua(tUa,g.Ee);g.Ua(I3,H3);I3.prototype.C=g.Ka;I3.prototype.KC=function(){this.C();I3.ye.KC.call(this)};
I3.prototype.bx=function(){this.C();I3.ye.bx.call(this)};
I3.prototype.GA=function(){this.C();I3.ye.GA.call(this)};
g.Ua(J3,I3);J3.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(K3,g.I);K3.prototype.Ra=function(a,b,c,d){c=(0,g.Ra)(c,d||this.u);a=g.wu(a,b,c);this.i.push(a);return a};
K3.prototype.qA=function(a,b,c,d){c=(0,g.Ra)(c,d||this.u);a=g.Nka(a,b,c);this.i.push(a);return a};
K3.prototype.yc=function(a){g.xu(a);g.ec(this.i,a)};
K3.prototype.xa=function(){g.xu(this.i);this.i.length=0;g.I.prototype.xa.call(this)};g.w(O3,g.rM);g.k=O3.prototype;g.k.load=function(){g.rM.prototype.load.call(this);if(!P3(this)){var a=g.Dua(this.player.getVideoData());a?(a=N3(a,vUa(this)),Q3(this,a,!1)):wUa(this)}};
g.k.unload=function(){Q3(this,null);this.B&&(this.B.abort(),this.B=null);g.rM.prototype.unload.call(this)};
g.k.tf=function(a,b){return P3(this)?"loadCustomEndscreenRenderer"===a?(a=N3(b,"new"),Q3(this,a),!0):null:null};
g.k.getOptions=function(){return P3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Ab=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<DVa.length;f++){var h=Math.abs(b.width-DVa[f]);if(-1===e||d>=h)e=f,d=h}d=EVa[e];this.u&&g.ln(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.zn(e.element,Math.round(h.width*a.width),f);g.sn(e.element,m,n);g.qr(e.element,FVa);m=h.left+h.width/2;h=h.top+l/2;g.N(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.qr(e.element,EVa);g.N(e.element,d);(e=g.dh(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.ln(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())X3(this,this.endscreen.impressionUrls),(a=g.Hx())&&this.endscreen.visualElement&&g.Yx(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.D[a];g.N(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.N(b,"ytp-ce-shown");X3(this,c.impressionUrls);(b=g.Hx())&&g.Yx(b,c.visualElement,void 0);this.player.U().B&&this.player.Qa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.pr(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.pr(b,"ytp-ce-shown");this.player.U().B&&this.player.Qa("endscreenelementhidden",a)}};
g.k.PX=function(a){var b=this;a.target===window&&(new g.L(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.qr(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var DVa=[346,426,470,506,570,640,853,1280,1920],EVa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),FVa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var GUa={G3:"current",W9:"new"};var IUa={CLOSE:"close",p$:"openUrl",SUBSCRIBE:"subscribe"},JUa={j0:"click",CLOSE:"close",c5:"hidden",Saa:"rollOut",Taa:"rollOver",Oba:"shown"};var zVa={j_:"anchored",RP:"branding",CHANNEL:"channel",F3:"cta",f5:"highlightText",H6:"label",PLAYLIST:"playlist",iaa:"popup",Xba:"speech",SUBSCRIBE:"subscribe",pca:"title",VIDEO:"video",Tda:"website"},yVa={RP:"branding",T_:"card",X3:"drawer",e5:"highlight",k8:"marker",uaa:"promotion",TEXT:"text",xea:"widget"};g.w(f4,g.I);g.k=f4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.Jy(a,b,{id:c,namespace:"annotations_module"});d&&this.Va.set(a,d);e&&this.Sa.set(a,e);this.context.I.Od([a])};
g.k.Ix=function(){this.context.u.subscribe("resize",this.Ry,this)};
g.k.LC=function(a,b,c,d,e,f){if(this.ib)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.th(this.element)};
g.k.Ry=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=Z3(a);if(f){var h=SUa(f,a.target),l=function(){a.i&&e.context.I.pauseVideo();var m=e.context.videoData.D||!1,n=g.tt(f||"");m&&n&&(n.v||n.list)?e.context.I.hk(n.v,b,n.list,!1):g.iL(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);v4(this.context.logger,c,l,d);RUa(f)||(c=g.Hx(),d=b.itct,c&&d&&g.cy(c,g.Dx(d)))}};
g.k.xa=function(){this.Va.clear();this.Sa.clear();g.I.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.J(this,a);return a.element};g.w(k4,f4);g.k=k4.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.An(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.Ry=function(){var a=this.isAvailable();g.Bn(this.element,a);g.O(this.context.I.getRootNode(),g.gT.IV_DRAWER_ENABLED,a);C3(this.I)};
g.k.destroy=function(){this.I.St(!1);try{this.I.getRootNode().removeChild(this.C)}catch(a){}g.Tu(this.Z);g.xu(this.ya);this.Na&&this.Na.dispose();this.D&&this.D.dispose();f4.prototype.destroy.call(this)};
g.k.AS=function(){if(this.B){v4(this.context.logger,p4(this).tracking.close);var a=g.Hx();a&&this.K&&g.cy(a,this.K);j4(this)}};
g.k.NS=function(){g.O(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.mU=function(){var a=g.Hx(),b=p4(this);b=b?b.Me:this.Me;a&&b&&g.ay(a,[b])};
g.k.lU=function(){var a=g.Hx(),b=p4(this);b=b?b.Me:this.Me;a&&b&&g.by(a,[b])};
g.k.qR=function(){var a=p4(this);v4(this.context.logger,a.tracking.bP);var b=g.Hx();b&&a&&g.ay(b,[a.gj,a.Me])};
g.k.nU=function(){var a=g.Hx(),b=p4(this);a&&b&&g.by(a,[b.gj])};
g.k.pR=function(a){var b=p4(this),c=g.Hx();this.i?a?(a=this.context.logger,v4(a,b.tracking.FB),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.gj&&g.cy(c,b.gj)):(a=this.context.logger,v4(a,b.tracking.FB),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.Me&&g.cy(c,b.Me)):(a=this.context.logger,v4(a,b.tracking.FB),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.Me&&g.cy(c,this.Me))};g.w(q4,f4);q4.prototype.Ix=function(){f4.prototype.Ix.call(this);fVa(this)};
q4.prototype.show=function(){f4.prototype.show.call(this);var a=g.Hx(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.ay(a,[g.Dx(b.itct)])};
q4.prototype.hide=function(){f4.prototype.hide.call(this);var a=g.Hx(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.by(a,[g.Dx(b.itct)])};g.w(r4,q4);
r4.prototype.show=function(){if(!this.isActive){q4.prototype.show.call(this);if(!this.K){g.N(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ia:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Bn(this.u,!1);var b=this.createElement({G:"div",Ia:["branding-img-container"]});b.appendChild(this.u);this.element.appendChild(b);(b=NUa(this.annotation))&&g4(this,this.u,b,this.annotation.id,
a.session_data);jVa(this,a);this.K=!0}g.Bn(this.element,!0);this.isActive=!0;this.u&&gVa(this,this.u)}};
r4.prototype.hide=function(){this.isActive&&(q4.prototype.hide.call(this),g.Bn(this.element,!1),this.isActive=!1)};
r4.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);q4.prototype.destroy.call(this)};g.w(s4,q4);g.k=s4.prototype;g.k.show=function(){this.isActive||(q4.prototype.show.call(this),this.X||(lVa(this),this.X=!0),g.Bn(this.element,!0),g.ni(function(){g.pr(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,u4(this),mVa(this),nVa(this,this.J))};
g.k.hide=function(){this.isActive&&(g.N(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.LC=function(a,b,c,d,e,f){return this.isCollapsed?!1:q4.prototype.LC.call(this,a,b,c,d,e,f)};
g.k.xT=function(a){this.S=!0;t4(this,500,a)};
g.k.wT=function(){this.S=!1;oVa(this)};
g.k.rT=function(a){a.stopPropagation();this.hide()};
g.k.sT=function(a){a.stopPropagation();u4(this);this.isCollapsed=!0;g.N(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();q4.prototype.destroy.call(this)};g.w(w4,g.rM);g.k=w4.prototype;g.k.tf=function(a,b){if(!CVa(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.W1(b))&&x4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(XUa(this.i,b),C3(this.player)),!0}return null};
g.k.getOptions=function(){return CVa(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Tq=function(){var a=this.player.U(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.IM||a.X.get(b.videoId)||g.PF(b)||g.QF(b)?!0:!1};
g.k.KA=function(){if(this.B){var a=this.player.fb().getVideoContentRect(!0);g.zn(this.B.element,a.width,a.height);g.sn(this.B.element,a.left,a.top)}if(this.i){var b=this.player.Ej();a=this.i;b=b.width;g.O(a.C,"iv-drawer-small",426>=b);g.O(a.C,"iv-drawer-big",1280<=b)}};
g.k.rR=function(a){rVa(this,a.state);g.U(a.state,2)&&(this.Hh()&&this.Lk()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.St(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.D=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Ct(h)&&h.responseXML?h.responseXML:null)&&(x4(b,h),g.N(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.rM.prototype.load.call(this);rVa(this,this.player.Bb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Zt()&&(a=uVa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.D=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().X.get(d);f&&vVa(e,f);f=f&&(f.Wy||f.yv);if(!c.vp||f)c.Va?sVa(this,c.Va,e):(this.El=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.El));
g.dM(this.player,this.B.element,4);this.KA();(f=g.PF(c))&&AVa(this,f);(f=g.QF(c))&&f.featuredChannel&&BVa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Va&&(this.El&&(this.player.removeEventListener("videodatachange",this.El),this.El=null),sVa(this,b.Va,a))};
g.k.unload=function(){this.player.gf("annotations_module");for(var a=g.q(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.K=null;this.i&&(this.i.destroy(),this.i=null,C3(this.player));this.S=!1;this.D&&(this.D.abort(),this.D=null);this.J={};this.u.hide();g.rM.prototype.unload.call(this);this.B.detach();this.El&&(this.player.removeEventListener("videodatachange",this.El),this.El=null)};
g.k.QN=function(a){a===this.player.getVideoData().videoId&&(this.loaded?wVa(this):this.load())};
g.k.Hh=function(){return!!this.i&&this.i.isAvailable()};
g.k.Lk=function(){this.Hh();return!!this.i&&this.i.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Hh();this.i&&(a?c?i4(this.i,c,b):i4(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):j4(this.i))};
g.k.St=function(a,b){this.player.ea(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.U().X.unsubscribe("vast_info_card_add",this.QN,this);g.pr(this.player.getRootNode(),g.gT.IV_DRAWER_OPEN);for(var a=this.X,b=0,c=a.length;b<c;b++)g.Ku.xi(a[b]);this.X.length=0;g.rM.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.J(this,a);return a.element};g.qM("annotations_module",w4);g.qM("creatorendscreen",O3);})(_yt_player);
